---
title: "hw5_jhk2201"
author: "joseph Kim"
date: "11/19/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(purrr)
library(ggplot2)

```

### Problem 1

##### Importing Dataset 
```{r, message=FALSE, warning=FALSE}
homicide_df = 
  read_csv("/Users/josephkim/Desktop/p8105_hw5_jhk2201/homicide-data.csv", na = c("", "Unknown")) %>%
  mutate(
    city_state = str_c(city,state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    )) %>%
  relocate(city_state) %>%
  filter(city_state != "TulsaAL")

```

The raw data is has 52,179 rows of data, with 12 variables. 


```{r, message=FALSE, warning=FALSE}
baltimore_df = homicide_df %>% 
    filter(city_state == "BaltimoreMD") 

baltimore_summary =
  baltimore_df %>% 
    summarize(
      unsolved = sum(resolution == "unsolved"), 
      n=n()
  )

baltimore_test = 
  prop.test(
    x = baltimore_summary %>%  pull(unsolved), 
    n = baltimore_summary %>%  pull(n))

baltimore_test %>% 
  broom::tidy()

```

Iterating across cities

```{r, message=FALSE, warning=FALSE}
prop_test_function = function(city_df){
  
  city_summary = 
    city_df %>% 
    summarize(
      unsolved = sum(resolution == "unsolved"), 
      n = n()
) 
  
city_test = 
  prop.test(
    x = city_summary %>% pull(unsolved),
    n = city_summary %>% pull(n))
  
  return(city_test)

}
 
prop_test_function(baltimore_df)

homicide_df %>%
  filter(city_state == "AlbuquerqueNM") %>% 
  prop_test_function()
```

Now, let's iterate across all cities.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
result_df = 
  homicide_df %>%
  nest(data = uid:resolution) %>%
  mutate(
    test_results = map(data, prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  ) %>%
  select(city_state, tidy_results) %>%
  unnest(tidy_results)
```

```{r, message=FALSE, warning=FALSE}
result_df %>%
  mutate(city_state = fct_reorder(city_state, estimate)) %>%
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

### Problem 2:

```{r}
long_study_df = tibble(
  filename = list.files("./data")) %>% 
  mutate(data = purrr::map(str_c("./data/", filename), read_csv)) %>% 
  unnest(data) %>% 
    separate(filename, c("Group", "Case", "csv")) %>% 
    mutate(
      Arm = recode(Group, con = "Control", exp = "Experimental")) %>% 
  pivot_longer(week_1:week_8, 
               names_to = "Week",
               values_to = "Data",
               names_prefix = "week_") %>% 
  mutate(Week = as.numeric(Week)) %>% 
  mutate(Case = as.numeric(Case)) %>% 
  select(Arm, Case, Week, Data )


plot_long = long_study_df %>% 
    ggplot(aes(x=Week, y=Data, group = Case, color=Arm)) + geom_line() + facet_grid(~Arm) +
    labs(
      x = "Week", 
      y = "Data point per Week",
      title = "Longitudinal Data for Treatment Arms") 

plot_long
```


### Problem 3: 

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

```

##### Writing Function

```{r}
iris_missing_function = function(x) {
  if (is_numeric(x)) {
    mean_nonmissing = round(mean(x, na.rm = TRUE, 1))
    x = replace_na(x, mean_nonmissing)}
  else if (is.character(x)) {
    x = replace_na(x, "virginica")}
  return(x)
}

iris_fillin = 
  map_df(iris_with_missing, iris_missing_function) %>% 
  as.tibble()

knitr::kable(iris_fillin)

view(iris_fillin)

```


